export const knowYourWiresLesson = {
  id: 'know-your-wires',
  title: 'Do You Know Your Electrical?',
  description: 'Wire colors, voltage, and gauge. Quick and easy.',
  questions: [
    {
      id: 'outlet-voltage',
      type: 'quiz',
      jobLabel: 'Voltage',
      narrative: 'Start with something every house has.',
      prompt: "What's the standard voltage for a household outlet in the US?",
      options: [
        { id: '12', label: '12V' },
        { id: '120', label: '120V' },
        { id: '240', label: '240V' },
        { id: '480', label: '480V' },
      ],
      correctOptionId: '120',
      explanation: 'Most household outlets run on 120 volts.',
    },
    {
      id: 'hot-wire',
      type: 'quiz',
      interaction: 'wires',
      jobLabel: 'Wire Colors',
      narrative: "Now let's open one up. Tap the wire that answers each question.",
      prompt: 'Which wire is "hot": energized and able to shock you?',
      options: [
        { id: 'white', label: 'White', shortLabel: 'White', color: '#DCD5C4' },
        { id: 'green', label: 'Green', shortLabel: 'Green', color: 'var(--green)' },
        { id: 'black', label: 'Black', shortLabel: 'Black', color: '#1A1A1A' },
        { id: 'bare', label: 'Bare copper', shortLabel: 'Bare', color: '#B5824B' },
      ],
      correctOptionId: 'black',
      explanation: 'Black is the hot wire. Always treat it as live.',
    },
    {
      id: 'ground-wire',
      type: 'quiz',
      interaction: 'wires',
      jobLabel: 'Wire Colors',
      narrative: 'Same box, next wire.',
      prompt: 'Which wire is the grounding conductor?',
      options: [
        { id: 'black', label: 'Black', shortLabel: 'Black', color: '#1A1A1A' },
        { id: 'white', label: 'White', shortLabel: 'White', color: '#DCD5C4' },
        { id: 'green', label: 'Green or bare copper', shortLabel: 'Green', color: 'var(--green)' },
        { id: 'red', label: 'Red', shortLabel: 'Red', color: 'var(--red)' },
      ],
      correctOptionId: 'green',
      explanation: 'Green or bare copper is the ground wire.',
    },
    {
      id: 'grounded-conductor',
      type: 'quiz',
      jobLabel: 'Code Terms',
      narrative: "This one trips up a lot of people. Codebooks don't say what you'd expect.",
      prompt: 'The white wire is technically called the "grounded conductor." What do electricians actually call it?',
      options: [
        { id: 'ground', label: 'Ground' },
        { id: 'hot', label: 'Hot' },
        { id: 'neutral', label: 'Neutral' },
        { id: 'ungrounded', label: 'Ungrounded' },
      ],
      correctOptionId: 'neutral',
      explanation: 'The white wire is neutral, even though the code calls it "grounded."',
    },
    {
      id: 'wire-gauge',
      type: 'quiz',
      jobLabel: 'Wire Gauge',
      narrative: 'Last one. This is a real jobsite mistake, not just trivia.',
      prompt: 'What wire gauge do you need for a standard 20-amp circuit?',
      options: [
        { id: '14', label: '14 AWG' },
        { id: '12', label: '12 AWG' },
        { id: '10', label: '10 AWG' },
        { id: '8', label: '8 AWG' },
      ],
      correctOptionId: '12',
      explanation: '12 AWG is the right size for a 20-amp circuit.',
    },
  ],
}
